version: '3.8'
services:
  write-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: advance_architecture
      POSTGRES_PASSWORD: advance_architecture
      POSTGRES_DB: advance_architecture
  read-db:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: 'vf-read-db'
  event-store:
    image: mongo:6.0.4
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
